name: td_2
description: "Tower defense"
publish_to: "none"
version: 0.0.2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  astar_dart:
    ^2.1.0
    # git: url: https://github.com/s1r1m1r1/astar_dart.git ref: develop
  audioplayers: ^6.1.1
  bloc: ^8.1.4
  bonfire: 3.13.0
  # bonfire: 3.12.2
  equatable: ^2.0.7
  fast_noise: ^1.0.1
  flame: ^1.21.0
  # flame: ^1.18.0
  flame_audio: ^2.10.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4

  get_it: ^8.0.3
  injectable: ^2.5.0
  logging: ^1.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.8.0
  #  flutter pub run intl_utils:generate
  intl_utils: ^2.8.5

  test: any

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/enemy/
    - assets/images/tile/
    - assets/images/itens/
    - assets/images/weapon/
    - assets/audio/music/
    - assets/audio/sfx/
# -------------------------------- int generate ----------------------------------------
flutter_intl:
  enabled: true
#  ------------------------------- Flutter GEN -----------------------------------------

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: false
    rive: false
    lottie: false

  assets:
    enabled: true

    outputs:
      class_name: Assets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    # exclude:
    # - assets-extern/*
    # - pictures/chip5.jpg
#  ------------------------------------------------------------------------------------

