name: td_2
description: "Tower defense"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^3.12.3
  fast_noise: ^1.0.1
  gif_view: ^0.4.0
  url_launcher: ^6.1.14
  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^2.4.4
  logging: ^1.3.0


dev_dependencies:
  test: any
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.2




# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/topdown/
    - assets/images/platform/
    - assets/images/platform/fox/
    - assets/images/platform/frog/
    - assets/images/player/
    - assets/images/enemy/
    - assets/images/npc/
    - assets/images/tile/
    - assets/images/tile_random/
    - assets/images/tiled/
    - assets/images/tiled/top_down/
    - assets/images/tiled/punnyworld/
    - assets/images/tiled/simple_topdown/
    - assets/images/tiled/tileset/
    - assets/images/itens/
    - assets/images/lpc/body/
    - assets/images/lpc/feet/
    - assets/images/lpc/hair/
    - assets/images/lpc/leg/
    - assets/images/lpc/torco/
    - assets/images/lpc/head/
    - assets/images/lpc/gloves/
    - assets/images/multi_scenario/tile/
    - assets/images/spritefusion/
    - assets/images/solaria/
    - assets/images/noise/
    - assets/images/weapon/
